steps:
  # Build and push the container image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--tag'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
          gcloud run deploy "${_SERVICE_NAME}" \
          --image "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}" \
          --add-cloudsql-instances "${PROJECT_ID}:${_REGION}:${_DATABASE_INSTANCE_NAME}" \
          --platform managed \
          --region "${_REGION}" \
          --allow-unauthenticated \
          --set-env-vars "NODE_ENV=production,FIREBASE_DISABLE_AUTH=false,FIREBASE_CHECK_REVOKED_TOKENS=true,DATABASE_URL=mysql://$$DATABASE_USERNAME:$$DATABASE_PASSWORD@localhost/ashbourne_scms?socket=/cloudsql/${PROJECT_ID}:${_REGION}:${_DATABASE_INSTANCE_NAME}" \
          --set-secrets ENCRYPTION_MASTER_KEY=ENCRYPTION_MASTER_KEY:latest
    secretEnv: ['DATABASE_USERNAME', 'DATABASE_PASSWORD']

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/DATABASE_USERNAME/versions/latest
      env: 'DATABASE_USERNAME'
    - versionName: projects/${PROJECT_ID}/secrets/DATABASE_PASSWORD/versions/latest
      env: 'DATABASE_PASSWORD'

# Set substitutions
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'ashbourne-scms-backend'
  _DATABASE_INSTANCE_NAME: 'ashbourne-scms-main-db-001'

# Set a longer timeout for the build
timeout: '1200s'